hostname router01

interface eth0
 shutdown

interface lo
 ip address 2.2.2.2/32
 

interface eth1
 ip address 192.168.1.2/30

ip prefix-list all_permit seq 5 permit any

router bgp 65001

  neighbor external peer-group
  neighbor external remote-as 65000
  neighbor 192.168.1.1 peer-group external

  address-family ipv4 unicast
   neighbor external prefix-list all_permit in
   neighbor external prefix-list all_permit out
   redistribute connected   
  exit-address-family

