hostname N1

log file /var/log/frr/frr.log 
!
# !debug bgp neighbor-events
debug bgp zebra
debug bgp evpn


interface eth0
 shutdown

interface lo
 ip address 100.0.0.2/32 

interface eth1
 ip address 192.168.2.2/24


ip prefix-list all_permit seq 5 permit any

ip route 0.0.0.0/0 192.168.2.1

router bgp 65002
  bgp router-id 192.168.2.2
  neighbor fabric peer-group
  neighbor fabric remote-as 65000
  neighbor fabric capability extended-nexthop
  neighbor fabric update-source 192.168.2.2
  neighbor 192.168.2.1 peer-group fabric

  address-family ipv4 unicast
    neighbor fabric activate
    redistribute connected
       neighbor fabric prefix-list all_permit in
          neighbor fabric prefix-list all_permit out
  exit-address-family
